dist: xenial
language: python
python:
- '3.7'
notifications:
  email: false
before_install:
- sudo add-apt-repository -y ppa:ubuntugis/ppa
- sudo apt-get update -y
- sudo apt install -y gdal-bin python-gdal python3-gdal
install:
- pip install -e .[dev]
script:
- black --check --exclude venv .
- pylint rest_framework_mvt/
- pytest --cov=rest_framework_mvt/ test/
after_success:
- coveralls
