name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  test:
    name: ${{ matrix.os }}, ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Build
        shell: bash
        run: |
            sudo add-apt-repository -y ppa:ubuntugis/ppa
            sudo apt-get update -y
            sudo apt install -y gdal-bin python3-gdal
            python -m pip install -e .[dev]
      - name: Lint
        shell: bash
        run: |
          black --check --exclude venv .
          pylint rest_framework_mvt/
      - name: Test
        shell: bash
        run: py.test --cov-report term-missing --cov=rest_framework_mvt --cov-report xml
      - uses: codecov/codecov-action@v1
